### ISSUE TITLE
Boolean turns into number

### ISSUE THREAD

**Issue by badsequel** [quandyfactory/dicttoxml#37] opened 2015-04-09 17:29 UTC
Hi, 

Ref this:
>Python -> XML
integer   int
long      long
float     float
Decimal   number
string    str
unicode   str
datetime  str
None      null
boolean   bool
list      list
set       list
tuple     list
dict      dict
>

This code produces the below xml. the <kid> element has a type attribute set to "number". Should be bool, if I am reading the above correctly and haven't missed something obvious. 

    from dicttoxml import dicttoxml

    aBool = bool(1) 
    aString = str("Bob")
    anInt = int(10)

    data = [
       { "person": {
       "name" : aString,"age":anInt, "kid": aBool}
       }
       ]

    xml = dicttoxml(data,attr_type = True, root=False) 
    xml_string = xml.decode('utf-8')

    print(xml_string)

```javascript
<item type="dict">
	<person type="dict">
		<kid type="number">True</kid>
		<name type="str">Bob</name>
		<age type="int">10</age>
	</person>
</item>
```

**Comment by quandyfactory** [comment] 2015-04-10 00:22
Thanks for catching this. It turns out that the test `isinstance(True, numbers.Number)` returns `True`. I modified the `get_xml_type()` function to test for boolean values before testing for numbers and the issue is fixed in version 1.6.5.

Note that I'm currently getting an `Upload failed (500): Internal Server Error` when I try to upload the newest version of dicttoxml to pypi, so for now you'll have to get the code from github.

**Comment by quandyfactory** [comment] 2015-04-10 00:25
So I incremented the version to 1.6.6, reinstalled it and re-uploaded it to pypi, and now it works. Not sure what the issue was with 1.6.5, but the newest version is now available both here on github and via pypi.

**Closed by quandyfactory** 2015-04-10 00:25 UTC

**Comment by badsequel** [comment] 2015-04-10 06:41
Fix confirmed. Thanx.
