### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Iterable'

### ISSUE THREAD

**Issue by albfan** [quandyfactory/dicttoxml#91] opened 2022-04-26 06:12 UTC
On python 3.10 

```
  File "/home/alberto/.local/lib/python3.10/site-packages/dicttoxml.py", line 235, in convert_dict
    elif isinstance(val, collections.Iterable):
```

it needs to be `collections.abc.Iterable` in several places instead of `collections.Iterable`

**Comment by dondelelcaro** [comment] 2022-04-27 22:06
Pull request #90 should fix this issue once it gets merged.

**Comment by ayanezeclac** [comment] 2022-06-02 20:25
I faced the same problem this week. The json to xml functionality was broken. Unfortunately this cool library doesn't seem to be maintained and I can't wait, so I added those lines in my app script and the problem is gone.

import collections
collections.Iterable = collections.abc.Iterable

regards

**Comment by quandyfactory** [comment] 2022-06-06 11:43
This issue has been fixed.

**Comment by quandyfactory** [comment] 2022-06-06 11:43
This issue has been fixed.

**Closed by quandyfactory** 2022-06-06 11:43 UTC

**Comment by RyuzakiKK** [comment] 2022-06-28 09:39
@quandyfactory is there an ETA for when the version 1.7.5 will be released on pypi?

**Comment by tomasserravento** [comment] 2022-08-29 00:33
@quandyfactory thank you so much for the fix. Could you please release 1.7.5 on pypy?

**Comment by astrochun** [comment] 2022-09-01 21:12
Came across this: https://github.com/quandyfactory/dicttoxml/issues/78#issuecomment-1234019636

It seems that there are still some needed changes?

A 1.7.5 release would be nice (this isn't difficult with a GitHub Actions to automate). Thank you.

**Comment by quandyfactory** [comment] 2022-10-11 07:03
I have been woefully negligent at maintaining this library, but will 
push an update within the next week to fix this issue.

**Comment by saikiranummigari** [comment] 2022-10-12 13:33
@quandyfactory can you please push 1.7.5 to pypi, please?

**Comment by kieranjol** [comment] 2022-10-25 15:50
A new version would be wonderful, would I be correct in thinking that this issue has been fixed here, just not on pypi? Do you need any assistance with maintenance?

**Comment by tomasserravento** [comment] 2022-10-25 16:22
> A new version would be wonderful, would I be correct in thinking that this issue has been fixed here, just not on pypi? Do you need any assistance with maintenance?

Hey, yes it has been fixed but not pushed on pypi. I hope they push this soon as it may help a lot of people!

As a temp fix you can put this code before using the plugin:
`import collections
collections.Iterable = collections.abc.Iterable`

**Comment by Namwanza** [comment] 2022-11-23 21:50
A simple fix that worked for python3.10:

Under directory **/usr/lib/python3.10/collections/__init__.p**y  
Addes this line of code:

`from _collections_abc import Iterable`

**Comment by quandyfactory** [comment] 2022-11-25 11:09
I am the worst maintainer in history, but dicttoxml 1.7.5 is finally pushed to pypi.
